// <auto-generated />
using System;
using CarteiraInvestimentos.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarteiraInvestimentos.Infrastructure.Migrations
{
    [DbContext(typeof(CarteiraInvestimentosContext))]
    [Migration("20251017195644_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("CarteiraInvestimentos.Domain.Entities.Ativo", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("DataPrimeiraCompra")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecoMedioCompra")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("QuantidadeTotal")
                        .HasColumnType("int");

                    b.HasKey("Codigo");

                    b.ToTable("Ativos");
                });

            modelBuilder.Entity("CarteiraInvestimentos.Domain.Entities.Transacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AtivoCodigo")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CodigoAtivo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("DataOperacao")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantidade")
                        .HasColumnType("int");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AtivoCodigo");

                    b.ToTable("Transacoes");
                });

            modelBuilder.Entity("CarteiraInvestimentos.Domain.Entities.Transacao", b =>
                {
                    b.HasOne("CarteiraInvestimentos.Domain.Entities.Ativo", null)
                        .WithMany("Transacoes")
                        .HasForeignKey("AtivoCodigo");
                });

            modelBuilder.Entity("CarteiraInvestimentos.Domain.Entities.Ativo", b =>
                {
                    b.Navigation("Transacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
